# Generated by Django 5.2.15 on 2026-06-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oraclesettings',
            name='name',
        ),
        migrations.AddField(
            model_name='oraclesettings',
            name='connection_mode',
            field=models.CharField(choices=[('sid', 'SID'), ('service_name', 'Service Name')], default='sid', max_length=20),
        ),
        migrations.AddField(
            model_name='oraclesettings',
            name='oracle_client_lib_dir',
            field=models.CharField(blank=True, help_text='مثال: C:\\Users\\user\\Pictures\\instantclient-basic-windows.x64-23.26.2.0.0\\instantclient_23_0', max_length=255),
        ),
        migrations.AddField(
            model_name='oraclesettings',
            name='sid',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='oraclesettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='oraclesettings',
            name='company_name',
            field=models.CharField(default='قارى الأسعار', max_length=150),
        ),
        migrations.AlterField(
            model_name='oraclesettings',
            name='service_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
