# Generated by Django 5.2.15 on 2026-06-17 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_activeusersession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoginPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_multiple_sessions', models.BooleanField(default=False, verbose_name='السماح بالدخول من أكثر من جهاز')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='login_policy', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'صلاحية دخول المستخدم',
                'verbose_name_plural': 'صلاحيات دخول المستخدمين',
            },
        ),
    ]
